import bodyParser from "body-parser";
import express from "express";
import * as BitcoinController from "./controllers/blockchainController";
const app = express();
app.use(bodyParser.json());
app.use(bodyParser.urlencoded({ extended: false }));
app.get("/blockchain", BitcoinController.getBitCoint);
app.post("/register-and-broadcast-node", BitcoinController.registerAndBroadcastNode);
app.post("/register-node", BitcoinController.registerNode);
app.post("/register-nodes-bulk", BitcoinController.registerNodesBulk);
app.post("/transaction/broadcast", BitcoinController.transactionBroadcast);
app.post("/transaction", BitcoinController.addTransaction);
app.post("/receive-new-block", BitcoinController.recieveNewBlock);
app.post("/regist-all-node", BitcoinController.registAllNode);
app.get("/consensus", BitcoinController.consensus);
app.get("/mine", BitcoinController.mine);
export default app;
